# Generated by Django 5.2.15 on 2026-06-14 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=64)),
                ('script_name', models.CharField(max_length=255)),
                ('script_text', models.TextField()),
                ('audio_path', models.TextField()),
                ('transcript', models.TextField(blank=True, null=True)),
                ('wer', models.FloatField(blank=True, null=True)),
                ('clarity', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('segments', models.TextField(blank=True, null=True)),
                ('cer', models.FloatField(blank=True, null=True)),
                ('artic_rate', models.FloatField(blank=True, null=True)),
                ('pause_ratio', models.FloatField(blank=True, null=True)),
                ('filled_pauses', models.FloatField(blank=True, null=True)),
                ('avg_conf', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-timestamp', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(db_index=True)),
                ('timestamp', models.CharField(db_index=True, max_length=64)),
                ('script_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_token', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hyp_token', models.CharField(blank=True, max_length=255, null=True)),
                ('op', models.CharField(db_index=True, max_length=32)),
                ('error_kind', models.CharField(db_index=True, max_length=64)),
                ('ref_start', models.IntegerField(blank=True, null=True)),
                ('ref_end', models.IntegerField(blank=True, null=True)),
                ('hyp_start', models.IntegerField(blank=True, null=True)),
                ('hyp_end', models.IntegerField(blank=True, null=True)),
                ('ref_local_start', models.IntegerField(blank=True, null=True)),
                ('ref_local_end', models.IntegerField(blank=True, null=True)),
                ('hyp_local_start', models.IntegerField(blank=True, null=True)),
                ('hyp_local_end', models.IntegerField(blank=True, null=True)),
                ('ref_token_len', models.IntegerField(blank=True, null=True)),
                ('hyp_token_len', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('segment_start', models.FloatField(blank=True, null=True)),
                ('segment_end', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'session_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImprovementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('word', 'Word'), ('sound', 'Sound'), ('character', 'Character'), ('position', 'Word Position'), ('phrase', 'Phrase'), ('fluency', 'Fluency')], max_length=32)),
                ('target_key', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('learning', 'Learning'), ('review', 'Review'), ('mastered', 'Mastered'), ('paused', 'Paused')], default='learning', max_length=32)),
                ('mastery', models.FloatField(default=0.0)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_at', '-updated_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='practice_im_kind_ef2191_idx'), models.Index(fields=['due_at'], name='practice_im_due_at_8cf523_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'target_key'), name='unique_card_target')],
            },
        ),
        migrations.CreateModel(
            name='PracticeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_session_id', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('error_rate', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='practice.improvementcard')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('source', models.CharField(choices=[('builtin', 'Built-in'), ('user', 'User'), ('imported', 'Imported'), ('generated', 'Generated')], default='user', max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=512)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('target_patterns', models.JSONField(blank=True, default=list)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['source', 'active'], name='practice_pr_source_c76269_idx'), models.Index(fields=['difficulty'], name='practice_pr_difficu_7797ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPracticeScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_provider', models.CharField(default='manual', max_length=64)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_scripts', to='practice.improvementcard')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_records', to='practice.practicescript')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
