# Generated by Django 5.2.15 on 2026-06-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_scoringjob_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_generation_provider', models.CharField(choices=[('local_template', 'Local template'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='local_template', max_length=32)),
                ('transcription_provider', models.CharField(choices=[('local_whisper', 'Local Whisper'), ('openai', 'OpenAI transcription'), ('uploaded_transcript', 'Transcript sidecar')], default='local_whisper', max_length=64)),
                ('openai_script_model', models.CharField(default='gpt-5.5', max_length=96)),
                ('anthropic_script_model', models.CharField(default='claude-sonnet-4-6', max_length=96)),
                ('openai_transcription_model', models.CharField(default='whisper-1', max_length=96)),
                ('autumn_base_url', models.URLField(blank=True, default='')),
                ('autumn_token_enc', models.BinaryField(blank=True, null=True)),
                ('openai_api_key_enc', models.BinaryField(blank=True, null=True)),
                ('anthropic_api_key_enc', models.BinaryField(blank=True, null=True)),
                ('codex_token_bundle_enc', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'practice settings',
            },
        ),
    ]
