# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_practicesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringjob",
            name="mode",
            field=models.CharField(
                choices=[
                    ("score", "Score against script"),
                    ("free_speak", "Free Speak transcription"),
                ],
                default="score",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="autumn_project",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="autumn_subprojects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_beam_size",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_chunk_seconds",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_condition_on_previous_text",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_device",
            field=models.CharField(
                choices=[("auto", "Auto"), ("cpu", "CPU"), ("gpu", "GPU")],
                default="auto",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_language",
            field=models.CharField(
                choices=[("auto", "Auto detect"), ("en", "English")],
                default="en",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_model_name",
            field=models.CharField(default="base.en", max_length=96),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_no_speech_threshold",
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_preset",
            field=models.CharField(
                choices=[
                    ("---", "Custom"),
                    ("fast_cpu", "Fast CPU"),
                    ("balanced_cpu", "Balanced CPU"),
                    ("balanced_gpu", "Balanced GPU"),
                    ("accurate_gpu", "Accurate GPU"),
                ],
                default="balanced_cpu",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_temperature",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="whisper_timestamps",
            field=models.BooleanField(default=True),
        ),
    ]
