# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0005_modes_and_whisper_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringjob",
            name="partial_transcript",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="practicesettings",
            name="autumn_active_session_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
