# Generated by Codex on 2026-06-16

from django.db import migrations, models


BUILTIN_DRILLS = [
    {
        "title": "Tongue Twister Level 1: Warm-Up",
        "body": "\n".join(
            [
                "Big brown bear.",
                "Clear calm communication.",
                "Perfect pronunciation.",
                "Crisp consonants carry clarity.",
                "Speak slowly, say sounds smoothly.",
            ]
        ),
        "difficulty": 1,
        "tags": ["builtin", "drill", "tongue-twister", "warm-up", "level-1"],
        "source_ref": "builtin:speech-drills:tongue-twister-level-1",
    },
    {
        "title": "Tongue Twister Level 2: Moderate",
        "body": "\n".join(
            [
                "Red lorry, yellow lorry.",
                "Toy boat, toy boat, toy boat.",
                "Freshly fried flying fish.",
                "Rolling waves roar loudly.",
                "Seven silent ships sailed southward.",
            ]
        ),
        "difficulty": 2,
        "tags": ["builtin", "drill", "tongue-twister", "moderate", "level-2"],
        "source_ref": "builtin:speech-drills:tongue-twister-level-2",
    },
    {
        "title": "Tongue Twister Level 3: Challenging",
        "body": "\n".join(
            [
                "Unique New York.",
                "Irish wristwatch, Swiss wristwatch.",
                "Six sleek swans swam swiftly southward.",
                "Black bugs' blood, blue bugs' blood.",
                "Truly rural, rarely regular.",
            ]
        ),
        "difficulty": 3,
        "tags": ["builtin", "drill", "tongue-twister", "challenging", "level-3"],
        "source_ref": "builtin:speech-drills:tongue-twister-level-3",
    },
    {
        "title": "Tongue Twister Level 4: Hard",
        "body": "\n".join(
            [
                "She sells seashells by the seashore.",
                "Peter Piper picked a peck of pickled peppers.",
                "A proper copper coffee pot.",
                "How can a clam cram in a clean cream can?",
                "A quick-witted cricket critic.",
            ]
        ),
        "difficulty": 4,
        "tags": ["builtin", "drill", "tongue-twister", "hard", "level-4"],
        "source_ref": "builtin:speech-drills:tongue-twister-level-4",
    },
    {
        "title": "Tongue Twister Level 5: Mastery",
        "body": "\n".join(
            [
                "The sixth sick sheik's sixth sheep's sick.",
                "Betty Botter bought some butter, but she said the butter's bitter.",
                "Greek grapes, Greek grapes, Greek grapes; Greek Greeks grow great Greek grapes.",
                "I slit a sheet, a sheet I slit, and on that slitted sheet I sit.",
                "Lesser leather never weathered wetter weather better.",
            ]
        ),
        "difficulty": 5,
        "tags": ["builtin", "drill", "tongue-twister", "mastery", "level-5"],
        "source_ref": "builtin:speech-drills:tongue-twister-level-5",
    },
]


def seed_builtin_drills(apps, schema_editor):
    PracticeScript = apps.get_model("practice", "PracticeScript")
    for drill in BUILTIN_DRILLS:
        PracticeScript.objects.update_or_create(
            source_ref=drill["source_ref"],
            defaults={
                "title": drill["title"],
                "author": "SpeechPractice",
                "body": drill["body"],
                "source": "builtin",
                "tags": drill["tags"],
                "target_patterns": [{"kind": "fluency", "target": "tongue-twister progression"}],
                "difficulty": drill["difficulty"],
                "active": True,
            },
        )


def remove_builtin_drills(apps, schema_editor):
    PracticeScript = apps.get_model("practice", "PracticeScript")
    PracticeScript.objects.filter(
        source="builtin",
        source_ref__startswith="builtin:speech-drills:",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_job_partials_and_autumn_timer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicescript",
            name="source",
            field=models.CharField(
                choices=[
                    ("builtin", "Built-in"),
                    ("user", "User"),
                    ("uploaded", "Uploaded"),
                    ("imported", "Imported"),
                    ("generated", "Generated"),
                ],
                default="user",
                max_length=32,
            ),
        ),
        migrations.RunPython(seed_builtin_drills, remove_builtin_drills),
    ]
