# Generated by Codex on 2026-06-16

from django.db import migrations, models


def classify_existing_scripts(apps, schema_editor):
    PracticeScript = apps.get_model("practice", "PracticeScript")
    PracticeScript.objects.filter(source="generated").update(practice_kind="drill")
    PracticeScript.objects.filter(
        source="builtin",
        source_ref__startswith="builtin:speech-drills:",
    ).update(practice_kind="drill")
    PracticeScript.objects.filter(title__startswith="Drill:").update(practice_kind="drill")


def reset_script_kinds(apps, schema_editor):
    PracticeScript = apps.get_model("practice", "PracticeScript")
    PracticeScript.objects.all().update(practice_kind="reading")


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0007_uploaded_source_and_builtin_drills"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicescript",
            name="practice_kind",
            field=models.CharField(
                choices=[("reading", "Reading script"), ("drill", "Drill")],
                default="reading",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="practicescript",
            index=models.Index(fields=["practice_kind", "active"], name="practice_pr_practic_f08408_idx"),
        ),
        migrations.RunPython(classify_existing_scripts, reset_script_kinds),
    ]
