# Generated by Codex on 2026-06-16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


BUILTIN_LADDER_REF = "builtin:speech-drills:tongue-twister-ladder"


def seed_builtin_ladder(apps, schema_editor):
    PracticeLadder = apps.get_model("practice", "PracticeLadder")
    PracticeLadderStep = apps.get_model("practice", "PracticeLadderStep")
    PracticeScript = apps.get_model("practice", "PracticeScript")
    ladder, _created = PracticeLadder.objects.update_or_create(
        source_ref=BUILTIN_LADDER_REF,
        defaults={
            "title": "Built-in Tongue Twister Ladder",
            "theme": "Tongue twisters for clarity, pacing, and articulation control.",
            "source": "builtin",
            "model_provider": "builtin",
            "auth_source": "builtin",
            "active": True,
        },
    )
    scripts = PracticeScript.objects.filter(
        source="builtin",
        practice_kind="drill",
        source_ref__startswith="builtin:speech-drills:tongue-twister-level-",
    ).order_by("difficulty", "title")
    for script in scripts:
        level = int(script.difficulty or 1)
        PracticeLadderStep.objects.update_or_create(
            ladder=ladder,
            level=level,
            defaults={
                "script": script,
                "title": script.title.replace("Tongue Twister ", ""),
                "focus": script.tags or [],
            },
        )


def remove_builtin_ladder(apps, schema_editor):
    PracticeLadder = apps.get_model("practice", "PracticeLadder")
    PracticeLadder.objects.filter(source_ref=BUILTIN_LADDER_REF).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0008_script_practice_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedpracticescript",
            name="auth_source",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="PracticeLadder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("theme", models.CharField(blank=True, max_length=512)),
                ("source", models.CharField(choices=[("builtin", "Built-in"), ("user", "User"), ("generated", "Generated")], default="user", max_length=32)),
                ("source_ref", models.CharField(blank=True, max_length=512)),
                ("model_provider", models.CharField(blank=True, max_length=96)),
                ("auth_source", models.CharField(blank=True, max_length=64)),
                ("prompt_snapshot", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cards", models.ManyToManyField(blank=True, related_name="practice_ladders", to="practice.improvementcard")),
            ],
            options={
                "ordering": ["source", "-created_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="PracticeLadderStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("focus", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ladder", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="practice.practiceladder")),
                ("script", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ladder_steps", to="practice.practicescript")),
            ],
            options={
                "ordering": ["ladder", "level"],
            },
        ),
        migrations.AddIndex(
            model_name="practiceladder",
            index=models.Index(fields=["source", "active"], name="practice_pr_source_43647a_idx"),
        ),
        migrations.AddIndex(
            model_name="practiceladder",
            index=models.Index(fields=["created_at"], name="practice_pr_created_30c8e2_idx"),
        ),
        migrations.AddIndex(
            model_name="practiceladderstep",
            index=models.Index(fields=["ladder", "level"], name="practice_pr_ladder__158977_idx"),
        ),
        migrations.AddConstraint(
            model_name="practiceladderstep",
            constraint=models.UniqueConstraint(fields=("ladder", "level"), name="unique_ladder_level"),
        ),
        migrations.RunPython(seed_builtin_ladder, remove_builtin_ladder),
    ]
