# Generated by Django 5.2.15 on 2026-06-24 10:31

from django.db import migrations, models


def create_legacy_history_tables(apps, schema_editor):
    """Create tables that predate Django when migrating a fresh database."""
    existing_tables = set(schema_editor.connection.introspection.table_names())
    for model_name in ("PracticeSession", "SessionError"):
        model = apps.get_model("practice", model_name)
        if model._meta.db_table not in existing_tables:
            schema_editor.create_model(model)
            existing_tables.add(model._meta.db_table)


def prefer_cloud_transcription(apps, schema_editor):
    PracticeSettings = apps.get_model("practice", "PracticeSettings")
    PracticeSettings.objects.filter(transcription_provider="local_whisper").update(
        transcription_provider="openai"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_practice_ladders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicesession',
            options={'ordering': ['-timestamp', '-id']},
        ),
        migrations.AlterModelOptions(
            name='sessionerror',
            options={},
        ),
        migrations.RunPython(
            create_legacy_history_tables,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RenameIndex(
            model_name='practiceladder',
            new_name='practice_pr_source_a0ea9b_idx',
            old_name='practice_pr_source_43647a_idx',
        ),
        migrations.RenameIndex(
            model_name='practiceladder',
            new_name='practice_pr_created_6d0aba_idx',
            old_name='practice_pr_created_30c8e2_idx',
        ),
        migrations.RenameIndex(
            model_name='practiceladderstep',
            new_name='practice_pr_ladder__11e315_idx',
            old_name='practice_pr_ladder__158977_idx',
        ),
        migrations.RenameIndex(
            model_name='practicescript',
            new_name='practice_pr_practic_bb5ab9_idx',
            old_name='practice_pr_practic_f08408_idx',
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='transcription_provider',
            field=models.CharField(choices=[('local_whisper', 'Local Whisper'), ('openai', 'OpenAI transcription'), ('uploaded_transcript', 'Transcript sidecar')], default='openai', max_length=64),
        ),
        migrations.RunPython(
            prefer_cloud_transcription,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
