# Generated by Django 5.2.15 on 2026-06-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_alter_practicesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringjob',
            name='submission_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
