# Generated by Django 5.2.15 on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0011_scoringjob_submission_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesession",
            name="self_review_notes",
            field=models.TextField(blank=True),
        ),
    ]
