# Generated by Django 5.2.15 on 2026-07-02 11:38

import django.db.models.deletion
import practice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_user_owned_workspaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedpracticescript',
            name='user',
            field=models.ForeignKey(default=practice.models.default_practice_user_pk, on_delete=django.db.models.deletion.CASCADE, related_name='generated_practice_scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='improvementcard',
            name='user',
            field=models.ForeignKey(default=practice.models.default_practice_user_pk, on_delete=django.db.models.deletion.CASCADE, related_name='improvement_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practicereview',
            name='user',
            field=models.ForeignKey(default=practice.models.default_practice_user_pk, on_delete=django.db.models.deletion.CASCADE, related_name='practice_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='user',
            field=models.ForeignKey(default=practice.models.default_practice_user_pk, on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practicesettings',
            name='user',
            field=models.OneToOneField(default=practice.models.default_practice_user_pk, on_delete=django.db.models.deletion.CASCADE, related_name='practice_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoringjob',
            name='user',
            field=models.ForeignKey(default=practice.models.default_practice_user_pk, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionerror',
            name='user',
            field=models.ForeignKey(default=practice.models.default_practice_user_pk, on_delete=django.db.models.deletion.CASCADE, related_name='practice_session_errors', to=settings.AUTH_USER_MODEL),
        ),
    ]
