# Generated by Django 5.2.15 on 2026-07-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0018_update_script_model_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesettings',
            name='autumn_active_session_id',
        ),
        migrations.RemoveField(
            model_name='practicesettings',
            name='autumn_base_url',
        ),
        migrations.RemoveField(
            model_name='practicesettings',
            name='autumn_project',
        ),
        migrations.RemoveField(
            model_name='practicesettings',
            name='autumn_subprojects',
        ),
        migrations.RemoveField(
            model_name='practicesettings',
            name='autumn_token_enc',
        ),
    ]
